cpu.o: cpu.c kernel.h ../include/ifem/config.h ../include/ifem/const.h \
  ../include/sys/types.h cpu.h const.h types.h globvars.h globfunc.h
i8259a.o: i8259a.c kernel.h ../include/ifem/config.h \
  ../include/ifem/const.h ../include/sys/types.h cpu.h const.h types.h \
  globvars.h globfunc.h
int.o: int.c kernel.h ../include/ifem/config.h ../include/ifem/const.h \
  ../include/sys/types.h cpu.h const.h types.h globvars.h globfunc.h
intrface.o: intrface.c kernel.h ../include/ifem/config.h \
  ../include/ifem/const.h ../include/sys/types.h cpu.h const.h types.h \
  globvars.h globfunc.h
irqhandl.o: irqhandl.c kernel.h ../include/ifem/config.h \
  ../include/ifem/const.h ../include/sys/types.h cpu.h const.h types.h \
  globvars.h globfunc.h
logdev.o: logdev.c kernel.h ../include/ifem/config.h \
  ../include/ifem/const.h ../include/sys/types.h cpu.h const.h types.h \
  globvars.h globfunc.h logdev.h
main.o: main.c kernel.h ../include/ifem/config.h \
  ../include/ifem/const.h ../include/sys/types.h cpu.h const.h types.h \
  globvars.h globfunc.h
varalloc.o: varalloc.c kernel.h ../include/ifem/config.h \
  ../include/ifem/const.h ../include/sys/types.h cpu.h const.h types.h \
  globvars.h globfunc.h
asmlib.o: asmlib.S cpu.h
isr.o: isr.S
segconst.o: segconst.S
startup.o: startup.S cpu.h
