# IFEM Utilities Makefile
# Author:		Bahman Movaqar (bmovaqar@yahoo.com)
# Last Revision:	Aug 23 2004, 20:54
#
include ../Makefile.conf
include Makefile.conf

OBJS=		$(UTIL_OBJS)

all: $(OBJS)

imgsize.o: imgsize.c

clean:
	@$(RM) -f *.o
