# IFEM Utilities Makefile
# Author:		Bahman Movaqar (bmovaqar@yahoo.com)
# Last Revision:	Aug 23 2004, 20:54
#
include ../Makefile.conf
include Makefile.conf

all: $(UTIL_BINS)

imgsize:
	@$(CC) $(CFLAGS) -o imgsize imgsize.c
clean:
	@$(RM) -f *.o
